.TH PBLOCKS 1 pblocks-VERSION
.SH NAME
pblocks \- modular status bar for dwm and other wm's
.SH SYNOPSIS
.B pblocks
.RI [ OPTIONS ]...
.SH DESCRIPTION
Pblocks helps to build very extensible status bars through use of scriptable modules and update signals.
.SH OPTIONS
.TP
.B \-c
path to the configuration file
.TP
.B \-d
delimiter to separate modules
.TP
.B \-s
output bar content to stdout
.TP
.B \-h
opens this man page
.TP
.B \-v
print current version
.SH CONFIGURATION
.P
The status bar is made from text output from command line programs.
Configuration file is loaded from
.I ~/.config/pblocks/pblocksrc
unless specified with
.BR \-c .
Config file must have next sections, separated with tabulations.
.RS
.B <update interval> <update signal> <command>
.RE
.P
To use icons add them directly to scripts or use
.B printf
.BI \&" <icon> %s\&"
.BI \&"$( <command> )"
as command, which is universal.
.P
Modules can have
.I unique
signals to update them only then their value changes instead of having them rerun on interval, which is more efficient.
.P
To update module with update signal
.I n
(where n can be from 1 to 22) you need to run
.RS
.B pkill
.BI \-RTMIN+ n
.B pblocks
.RE
.P
Or next command which is faster (where
.IR m = n +34)
.RS
.B kill
.BI \- m
.B $(pidof \-x pblocks)
.RE
.SH EXAMPLES
.TP
To setup the volume module with update signal 10 you need to put next command along side your volume bindings, so module will update only when volume changes, instead of constantly checking it's value.
.B pkill \-RTMIN+10 pblocks
.P
Update dwm bar with
.I xprop
instead of
.IR xsetroot ,
although pblocks by default uses xprop instead of xsetroot if it is not present.
.RS
.B pblocks -s | while read -r bar; do xprop -root -set WM_NAME \&"$bar\&"; done
.RE
.SH AUTHOR
Written by Zubarev Grigoriy
.RI < thirtysix@thirtysix.pw >
in 2023
.SH LICENSE
General Public License v3 or later
.SH SEE ALSO
.BR pkill (1),
.BR xsetroot (1),
.BR xprop (1),
.BR dwm (1)
