.TH PBLOCKS 1 pblocks-VERSION
.SH NAME
pblocks \- modular status bar for dwm and other wm's
.SH SYNOPSIS
.B pblocks
.RI [ OPTIONS ]...
.SH DESCRIPTION
Pblocks helps to build very extensible status bars through use of scriptable modules and update signals.
.SH OPTIONS
.TP
.B \-c
path to the configuration file
.TP
.B \-d
delimiter to separate modules
.TP
.B \-D
command to display bar
.RI ( %bar%
will be replaced with bar content, see examples)
.TP
.B \-s
output bar content to stdout
.TP
.B \-h
opens this man page
.TP
.B \-v
print current version
.SH CONFIGURATION
.P
The status bar is made from text output from command line programs.
Configuration file is loaded from
.I ~/.config/pblocks/pblocksrc
unless specified with
.BR \-c .
Config file must have next sections, separated with tabulations.
.RS
.B <icon> <update interval> <update signal> <command>
.RE
.P
Modules can have
.I unique
signals to update them only then their value changes instead of having them rerun on interval, which is more efficient.
.P
To update module with update signal
.I n
(where n can be from 1 to 22) you need to run
.RS
.B pkill
.BI \-RTMIN+ n
.B \-x pblocks
.RE
.P
Or next command which is faster (where
.IR m = n +34)
.RS
.B kill
.BI \- m
.B $(pidof \-x pblocks)
.RE
.SH EXAMPLES
.TP
To setup the volume module with update signal 10 you need to put next command along side your volume bindings, so module will update only when volume changes, instead of constantly checking it's value.
.B pkill \-RTMIN+10 \-x pblocks
.P
Update dwm bar with
.I xprop
instead of
.IR xsetroot .
Note that special characters need to be escaped
.IR twice .
.\" pblocks -D "xprop -root -set WM_NAME \\\"%bar%\\\""
.RS
.B pblocks -D \&"xprop -root -set WM_NAME \\\\\\\\\\\\\&"%bar%\\\\\\\\\\\\\&"\&"
.RE
.SH AUTHOR
Written by Zubarev Grigoriy
.RI < thirtysix@thirtysix.pw >
in 2023
.SH LICENSE
General Public License v3 or later
.SH SEE ALSO
.BR pkill (1),
.BR xsetroot (1),
.BR dwm (1)
