#!/bin/sh

# pblocks - modular status bar for dwm (and other wm's)

for file in "${XDG_CONFIG_HOME:-$HOME/.config}/pblocks/config" "${0%/*}/config"; do
    [ -f "$file" ] && config="$file" && break
done
[ -z "$config" ] && echo "Config not found." >&2 && exit 1

display() { eval "xsetroot -name \"$bar\"" ;}

temp="$(mktemp /tmp/XXX.pblocks)"
trap 'rm -f $temp' HUP INT QUIT TERM PWR EXIT
grep -v -e'^#' -e'^[\s\t]*$' "$config" > "$temp"

bar=""
delim=" "
sec=0

while :; do
    [ $sec -ne 0 ] && sleep 1 &
    wait && {
        id=0
        while read -r ico interv sig cmd; do
            if [ $sec -eq 0 ]; then
                eval "update$id() { block$id=\$(setsid -f $cmd) ;}"
                [ "$interv" -eq 0 ]  && "update$id" && display

                bar="${bar:+$bar$delim}$ico\${block$id}"

                # shellcheck disable=SC2064
                trap "update$id && display" "RTMIN+$sig"
            fi
            # update block if seconds divide by interval
            [ "$interv" -ne 0 ] && [ $((sec % interv)) -eq 0 ] && "update$id" && display
            id=$((id + 1))
        done < "$temp"
        sec=$((sec + 1))
    }
done
